use std::sync::Arc;

use arrow_schema::{DataType, Field, Schema};

pub fn experiment_capsule_v1_schema() -> Arc<Schema> {
    Arc::new(Schema::new(vec![
        Field::new("schema_version", DataType::Utf8, false),
        Field::new("run_id", DataType::Utf8, false),
        Field::new("record_kind", DataType::Utf8, false),
        Field::new("ordinal", DataType::Int64, false),
        Field::new("model_id", DataType::Utf8, false),
        Field::new("source_framework", DataType::Utf8, false),
        Field::new("source_revision", DataType::Utf8, false),
        Field::new("candidate_id", DataType::Utf8, false),
        Field::new("provider_id", DataType::Utf8, false),
        Field::new("decoder", DataType::Utf8, false),
        Field::new("environment_id", DataType::Utf8, false),
        Field::new("evaluation_input_id", DataType::Utf8, false),
        Field::new("git_commit", DataType::Utf8, false),
        Field::new("provider_registered", DataType::Boolean, false),
        Field::new("provider_execution_proven", DataType::Boolean, true),
        Field::new("provider_assignment_proven", DataType::Boolean, true),
        Field::new("fallback_detected", DataType::Boolean, true),
        Field::new("sample_id", DataType::Utf8, true),
        Field::new("dataset_id", DataType::Utf8, true),
        Field::new("dataset_repo_id", DataType::Utf8, true),
        Field::new("dataset_revision", DataType::Utf8, true),
        Field::new("audio_sha256", DataType::Utf8, true),
        Field::new("audio_duration_sec", DataType::Float64, true),
        Field::new("sample_rate_hz", DataType::Int64, true),
        Field::new("reference_text", DataType::Utf8, true),
        Field::new("hypothesis_text", DataType::Utf8, true),
        Field::new("normalized_text", DataType::Utf8, true),
        Field::new("cer", DataType::Float64, true),
        Field::new("wer", DataType::Float64, true),
        Field::new("audio_decode_ms", DataType::Float64, true),
        Field::new("resample_ms", DataType::Float64, true),
        Field::new("inference_ms", DataType::Float64, true),
        Field::new("decoder_ms", DataType::Float64, true),
        Field::new("postprocess_ms", DataType::Float64, true),
        Field::new("total_ms", DataType::Float64, true),
        Field::new("rtf", DataType::Float64, true),
        Field::new("peak_ram_mb", DataType::Float64, true),
        Field::new("peak_device_memory_mb", DataType::Float64, true),
        Field::new("status", DataType::Utf8, true),
        Field::new("error_code", DataType::Utf8, true),
        Field::new("error_stage", DataType::Utf8, true),
        Field::new("error_message", DataType::Utf8, true),
        Field::new("metric_name", DataType::Utf8, true),
        Field::new("metric_value", DataType::Float64, true),
        Field::new("metric_unit", DataType::Utf8, true),
    ]))
}
