use std::sync::Arc;

use arrow_schema::{DataType, Field, Schema};

pub fn experiment_capsule_v1_schema() -> Arc<Schema> {
    Arc::new(Schema::new(vec![
        Field::new("schema_version", DataType::Utf8, false),
        Field::new("run_id", DataType::Utf8, false),
        Field::new("record_kind", DataType::Utf8, false),
        Field::new("ordinal", DataType::Int64, false),
        Field::new("name", DataType::Utf8, true),
        Field::new("category", DataType::Utf8, true),
        Field::new("metadata_json", DataType::Utf8, true),
        Field::new("sample_id", DataType::Utf8, true),
        Field::new("dataset_id", DataType::Utf8, true),
        Field::new("dataset_repo_id", DataType::Utf8, true),
        Field::new("dataset_revision", DataType::Utf8, true),
        Field::new("subset", DataType::Utf8, true),
        Field::new("split", DataType::Utf8, true),
        Field::new("audio_sha256", DataType::Utf8, true),
        Field::new("audio_duration_sec", DataType::Float64, true),
        Field::new("sample_rate_hz", DataType::Int32, true),
        Field::new("reference_text", DataType::Utf8, true),
        Field::new("hypothesis_text", DataType::Utf8, true),
        Field::new("normalized_text", DataType::Utf8, true),
        Field::new("cer", DataType::Float64, true),
        Field::new("wer", DataType::Float64, true),
        Field::new("provider_id", DataType::Utf8, true),
        Field::new("decoder", DataType::Utf8, true),
        Field::new("load_ms", DataType::Float64, true),
        Field::new("session_creation_ms", DataType::Float64, true),
        Field::new("audio_decode_ms", DataType::Float64, true),
        Field::new("resample_ms", DataType::Float64, true),
        Field::new("frontend_ms", DataType::Float64, true),
        Field::new("encoder_ms", DataType::Float64, true),
        Field::new("inference_ms", DataType::Float64, true),
        Field::new("decoder_ms", DataType::Float64, true),
        Field::new("postprocess_ms", DataType::Float64, true),
        Field::new("total_ms", DataType::Float64, true),
        Field::new("rtf", DataType::Float64, true),
        Field::new("peak_ram_mb", DataType::Float64, true),
        Field::new("peak_device_memory_mb", DataType::Float64, true),
        Field::new("status", DataType::Utf8, true),
        Field::new("error_code", DataType::Utf8, true),
        Field::new("error_stage", DataType::Utf8, true),
        Field::new("error_message", DataType::Utf8, true),
        Field::new("metric_name", DataType::Utf8, true),
        Field::new("metric_value", DataType::Float64, true),
        Field::new("metric_unit", DataType::Utf8, true),
        Field::new("artifact_id", DataType::Utf8, true),
        Field::new("artifact_name", DataType::Utf8, true),
        Field::new("mime_type", DataType::Utf8, true),
        Field::new("artifact_sha256", DataType::Utf8, true),
        Field::new("artifact_size_raw", DataType::Int64, true),
        Field::new("artifact_part_index", DataType::Int32, true),
        Field::new("artifact_part_count", DataType::Int32, true),
        Field::new("artifact_offset", DataType::Int64, true),
        Field::new("artifact_part_sha256", DataType::Utf8, true),
        Field::new("payload", DataType::Binary, true),
    ]))
}
